// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbARugYqpirrXuI7qXp3s2PQAki1Vu76w',
    appId: '1:1017347826641:web:49cf15d30be64fd391b6f0',
    messagingSenderId: '1017347826641',
    projectId: 'chatbox-8f503',
    authDomain: 'chatbox-8f503.firebaseapp.com',
    storageBucket: 'chatbox-8f503.firebasestorage.app',
    measurementId: 'G-FFCZ5MV4SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsd7sLelUjNWBsUYxvbOou3ApEY0MAL-M',
    appId: '1:1017347826641:android:60eccc4a8d50632491b6f0',
    messagingSenderId: '1017347826641',
    projectId: 'chatbox-8f503',
    storageBucket: 'chatbox-8f503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLVmkdccR-3GM9CfCa-IHI5ClsYUAgGo',
    appId: '1:1017347826641:ios:c36642ee1fbef8a391b6f0',
    messagingSenderId: '1017347826641',
    projectId: 'chatbox-8f503',
    storageBucket: 'chatbox-8f503.firebasestorage.app',
    iosBundleId: 'com.example.Chatboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLVmkdccR-3GM9CfCa-IHI5ClsYUAgGo',
    appId: '1:1017347826641:ios:c36642ee1fbef8a391b6f0',
    messagingSenderId: '1017347826641',
    projectId: 'chatbox-8f503',
    storageBucket: 'chatbox-8f503.firebasestorage.app',
    iosBundleId: 'com.example.Chatboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbARugYqpirrXuI7qXp3s2PQAki1Vu76w',
    appId: '1:1017347826641:web:4a8c690e6d70c73f91b6f0',
    messagingSenderId: '1017347826641',
    projectId: 'chatbox-8f503',
    authDomain: 'chatbox-8f503.firebaseapp.com',
    storageBucket: 'chatbox-8f503.firebasestorage.app',
    measurementId: 'G-Y3NYN4D58Z',
  );
}
